import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";

const assets=path.join(process.argv[2],"webview/assets");
const file=fs.readdirSync(assets).find(n=>/^app-initial-.*\.js$/.test(n));
const source=fs.readFileSync(path.join(assets,file),"utf8");
const start=source.indexOf('const MTKdotLifecyclePolicy=1;');
const end=source.indexOf('function wEn(',start);
assert.ok(start>=0&&end>start,"dot helper owned boundary");
const helper=source.slice(start,end);
const id="11111111-2222-4333-8444-555555555555",dot="opaque-example-dot~instance";
let snapshot={entries:[{kind:"agent",taskId:id,data:{name:"Example Dot",orbitId:dot,protectDeletion:true,protectReboot:true}}]};
const g={__MTK_AGENT_ROSTER__:{current:()=>snapshot}};
const Nd=Symbol("dot-metadata");
Function("globalThis","Nd",helper)(g,Nd);
const policy=g.__MTK_DOT_POLICY__;
const scope={query:{getData:(q,t)=>q===Nd&&t===id?{id:dot}:null}};
assert.equal(policy.protected("delete",dot),true);
assert.equal(policy.protected("reboot",dot),true);
assert.equal(policy.protected("delete","other-dot"),false);
assert.equal(policy.protected("delete",dot,"another-conversation"),true,"cloud identity protects every room owned by this dot");
assert.equal(policy.protected("reboot",null,id),true,"configured room is protected before cloud metadata loads");
assert.equal(policy.protected("reboot","other-dot",id),false,"current cloud identity wins over stale room association");
assert.throws(()=>policy.assertReboot(scope,id),/protected/);
assert.doesNotThrow(()=>policy.assertReboot(scope,"other-thread"));
assert.equal(policy.nameForThread(id,"Native Name"),"Native Name");
assert.equal(policy.nameForThread(id,null),"Example Dot");
assert.equal(policy.nameForThread("other-thread","Native Name"),null,"never classify by name alone");
snapshot={entries:[{kind:"agent",taskId:id,data:{name:"Example Dot",orbitId:dot,protectDeletion:false,protectReboot:false}}]};
assert.equal(policy.protected("delete",dot),false,"policy reload takes effect immediately");
assert.doesNotThrow(()=>policy.assertReboot(scope,id));
snapshot={entries:[{kind:"agent",taskId:id,data:{name:"Example Dot",orbitId:dot,protectDeletion:true,protectReboot:true}}]};

// Test the exact injected entry guard without invoking a real remote mutation.
const deleteGuard=source.slice(source.indexOf("function wEn("),source.indexOf("let i=",source.indexOf("function wEn(")));
let sideEffects=0;
const invoke=Function("MTKdotProtected","sideEffects",`${deleteGuard}sideEffects();}return wEn;`)(policy.protected,()=>{sideEffects++});
invoke(null,dot,null,null);
assert.equal(sideEffects,0,"protected deletion returns before stock side effects");
invoke(null,"other-dot",null,null);
assert.equal(sideEffects,1,"unprotected deletion retains stock entry path");
assert.ok(source.includes('if(MTKdotProtected("delete",t)||!d()||e.get(eje,i).has(n.threadId))return;'),"retry checks current policy before mutation");
const rebootFile=fs.readdirSync(assets).find(n=>/^reboot-dialog-.*\.js$/.test(n));
const reboot=fs.readFileSync(path.join(assets,rebootFile),"utf8");
assert.ok(reboot.includes('f=async()=>{globalThis.__MTK_DOT_POLICY__.assertReboot(d,c);await(await y.postResponse('));
assert.ok(reboot.includes('assertRequestCurrent:()=>{globalThis.__MTK_DOT_POLICY__.assertReboot(d,c);'),"request-time recheck covers a previously opened dialog");
const mutationStart=reboot.indexOf("f=async()=>{")+2;
const mutationEnd=reboot.indexOf(".body?.cancel()}",mutationStart)+".body?.cancel()}".length;
const mutation=reboot.slice(mutationStart,mutationEnd);
let requests=0;
const transport={async postResponse(route,options){requests++;options.assertRequestCurrent();return {body:{cancel(){}}}}};
const d={...scope,get(key){if(key==="enabled")return true;if(key==="selected")return id;return false}};
const run=Function("globalThis","d","c","i","o","y","O","a","A",`return (${mutation})`)(g,d,id,"account","user",transport,"enabled","disabled","selected");
await assert.rejects(run(),/protected/);
assert.equal(requests,0,"protected reboot never reaches transport");
snapshot={entries:[]};
await run();
assert.equal(requests,1,"unprotected reboot preserves native transport");
transport.postResponse=async(route,options)=>{snapshot={entries:[{kind:"agent",taskId:id,data:{name:"Example Dot",orbitId:dot,protectReboot:true}}]};options.assertRequestCurrent();throw Error("request should have been refused")};
await assert.rejects(run(),/protected/,"policy enabled during request preparation is rechecked");
snapshot={entries:[{kind:"agent",taskId:id,data:{name:"Example Dot",orbitId:dot,protectDeletion:"yes"}}]};
assert.throws(()=>policy.protected("delete",dot),/Invalid TMTK dot policy/);
assert.equal(policy.nameForThread(id,"Native Name"),null,"malformed policy cannot crash name rendering");
console.log("dot lifecycle behavior probe passed");
