export const linuxBuild9647 = {
  name: "Linux build-9647",
  suffix: "9647Linux",
  react: "X0",
  jsx: "Z0",
  intl: "il",
  contracts: [
    "function KKn(e){let t=(0,XKn.c)(133),",
    "{desktopNavItemsEnabled:n,sidebarTriggerState:r}=e,",
    "[x,S]=(0,X0.useState)(0),C=il(),w=Rb(Zae),",
    "}else ge=t[51];let _e=ge.length>0",
    '(0,Z0.jsxs)(`div`,{className:`ms-auto flex items-center gap-1`,children:[(0,Z0.jsx)(o_n,{}),(0,Z0.jsx)(vJ,{showCustomizeSidebarAction:Se,children:(0,Z0.jsx)(iCn,{})}),!T&&le===`header_icon`?(0,Z0.jsx)(UCn,{sidebarMode:Z}):null]})',
    '(0,Z0.jsx)(ACn,{showCustomizeSidebarAction:Se,sidebarMode:Z,showSearchNavItem:!1})',
    "t[84]!==p||t[85]!==_||t[86]!==T||t[87]!==le||t[88]!==q||t[89]!==Ce||t[90]!==Se||t[91]!==Z?(",
    "t[84]=p,t[85]=_,t[86]=T,t[87]=le,t[88]=q,t[89]=Ce,t[90]=Se,t[91]=Z,t[92]=Ne):Ne=t[92]"
  ],
  applied: [
    'const MTK_SIDEBAR_ACTIONS_STORAGE_KEY="the-mechanics-toolkit:sidebar-global-actions-collapsed:v1"',
    "function MTKuseSidebarActionCollapse9647Linux()",
    "function MTKsidebarActionDisclosure9647Linux({collapsed:e,onToggle:t}){let n=il(),r=n.formatMessage",
    "function MTKsidebarCollapsedDestinations9647Linux(",
    'className:"flex size-8 items-center justify-center rounded-md text-secondary hover:bg-tertiary hover:text-primary cursor-pointer"',
    "function KKn(e){let t=(0,XKn.c)(134),",
    "[MTKsidebarActionsCollapsed,MTKtoggleSidebarActions]=MTKuseSidebarActionCollapse9647Linux()",
    "ge=MTKsidebarCollapsedDestinations9647Linux(MTKsidebarActionsCollapsed,ge,FT.projects);let _e=ge.length>0",
    "MTKsidebarActionsCollapsed?null:(0,Z0.jsx)(ACn,",
    '!T&&le===`header_icon`?(0,Z0.jsx)(UCn,{sidebarMode:Z}):null,(0,Z0.jsx)(MTKsidebarActionDisclosure9647Linux,{collapsed:MTKsidebarActionsCollapsed,onToggle:MTKtoggleSidebarActions})]})',
    "t[133]!==MTKsidebarActionsCollapsed",
    "t[133]=MTKsidebarActionsCollapsed,t[92]=Ne"
  ],
  ownerBefore: "function KKn(e){let t=(0,XKn.c)(133),",
  ownerAfter: "function KKn(e){let t=(0,XKn.c)(134),",
  stateBefore: "{desktopNavItemsEnabled:n,sidebarTriggerState:r}=e,",
  destinationBefore: "}else ge=t[51];let _e=ge.length>0",
  destinationAfter: "}else ge=t[51];ge=MTKsidebarCollapsedDestinations9647Linux(MTKsidebarActionsCollapsed,ge,FT.projects);let _e=ge.length>0",
  headerBefore: '(0,Z0.jsxs)(`div`,{className:`ms-auto flex items-center gap-1`,children:[(0,Z0.jsx)(o_n,{}),(0,Z0.jsx)(vJ,{showCustomizeSidebarAction:Se,children:(0,Z0.jsx)(iCn,{})}),!T&&le===`header_icon`?(0,Z0.jsx)(UCn,{sidebarMode:Z}):null]})',
  headerAfter: '(0,Z0.jsxs)(`div`,{className:`ms-auto flex items-center gap-1`,children:[(0,Z0.jsx)(o_n,{}),(0,Z0.jsx)(vJ,{showCustomizeSidebarAction:Se,children:(0,Z0.jsx)(iCn,{})}),!T&&le===`header_icon`?(0,Z0.jsx)(UCn,{sidebarMode:Z}):null,(0,Z0.jsx)(MTKsidebarActionDisclosure9647Linux,{collapsed:MTKsidebarActionsCollapsed,onToggle:MTKtoggleSidebarActions})]})',
  actionBefore: '(0,Z0.jsx)(ACn,{showCustomizeSidebarAction:Se,sidebarMode:Z,showSearchNavItem:!1})',
  memoBefore: "t[84]!==p||t[85]!==_||t[86]!==T||t[87]!==le||t[88]!==q||t[89]!==Ce||t[90]!==Se||t[91]!==Z?(",
  memoAfter: "t[84]!==p||t[85]!==_||t[86]!==T||t[87]!==le||t[88]!==q||t[89]!==Ce||t[90]!==Se||t[91]!==Z||t[133]!==MTKsidebarActionsCollapsed?(",
  assignmentBefore: "t[84]=p,t[85]=_,t[86]=T,t[87]=le,t[88]=q,t[89]=Ce,t[90]=Se,t[91]=Z,t[92]=Ne):Ne=t[92]",
  assignmentAfter: "t[84]=p,t[85]=_,t[86]=T,t[87]=le,t[88]=q,t[89]=Ce,t[90]=Se,t[91]=Z,t[133]=MTKsidebarActionsCollapsed,t[92]=Ne):Ne=t[92]"
};
